### ISSUE TITLE
panel login time out

### ISSUE THREAD

**Issue by xxspobbixx** [ToxicMushroom/Melijn#224]
**Describe the bug**

**To Reproduce**

**Expected behavior**
After I want to log in with discord, the time out screen from cloudflare appears.

**Screenshots**

![Screenshot_20240103_010508_Chrome](https://github.com/ToxicMushroom/Melijn/assets/56563710/a761d9d1-a32b-4ef7-b381-61a111ebdc51)

Screenshot: 

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S22]
 - OS: [Android 14 ]
 - Browser [Chrome]
 - Version [120]

**Additional context**

**Comment by ToxicMushroom** [comment]
should be back up, ty for reporting
